# Generated by Django 2.2.7 on 2019-11-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livecoding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultatcompo',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='resultatcompo',
            name='resultat_exercice',
        ),
        migrations.RemoveField(
            model_name='resultatcompo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='resultatexercice',
            name='exercice',
        ),
        migrations.RemoveField(
            model_name='resultatexercice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='testvalidation',
            name='exercice',
        ),
        migrations.DeleteModel(
            name='Exercice',
        ),
        migrations.DeleteModel(
            name='ResultatCompo',
        ),
        migrations.DeleteModel(
            name='ResultatExercice',
        ),
        migrations.DeleteModel(
            name='TestValidation',
        ),
    ]
