# Generated by Django 2.2.7 on 2019-11-20 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_profile_moyenne_generale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='moyenne_generale',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
