# Generated by Django 2.2.7 on 2019-11-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='niveau',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='specialisation',
        ),
        migrations.RemoveField(
            model_name='ressources',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='resultatcompos',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userspecialite',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='userspecialite',
            name='user',
        ),
        migrations.DeleteModel(
            name='Composition',
        ),
        migrations.DeleteModel(
            name='Cours',
        ),
        migrations.DeleteModel(
            name='Niveau',
        ),
        migrations.DeleteModel(
            name='Ressources',
        ),
        migrations.DeleteModel(
            name='ResultatCompos',
        ),
        migrations.DeleteModel(
            name='Specialisation',
        ),
        migrations.DeleteModel(
            name='UserSpecialite',
        ),
    ]
