# Generated by Django 2.2.7 on 2019-11-20 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='niveau',
            options={'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
        migrations.AlterModelOptions(
            name='resultatcompos',
            options={'verbose_name': 'ResultatCompos', 'verbose_name_plural': 'ResultatCompos'},
        ),
        migrations.AlterModelOptions(
            name='userspecialite',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
        migrations.AddField(
            model_name='userspecialite',
            name='moyenne_generale',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
