# Generated by Django 2.2.7 on 2019-11-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialisation', '0002_auto_20191120_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultatcompos',
            options={'verbose_name': 'ResultatCompos', 'verbose_name_plural': 'ResultatComposs'},
        ),
    ]
